kafka:
  host: "localhost"
  port: 9080
  parse_requested_topic_name: "parse_requested"
  price_measured_topic_name: "price_measured"
  group_id: "parsing_service_group"

http:
  addr: ":8070"

parser:
  user_agent: "price-tracker-parsing/1.0"
  request_timeout_ms: 8000
  max_body_bytes: 5242880
  retries: 3
  min_backoff_ms: 200
  max_backoff_ms: 2000
  per_domain_min_interval_ms: 300

swagger:
  enabled: false
  path: "/swagger"
