version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: parsing-kafka
    environment:
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9080,PLAINTEXT_DOCKER://:9070,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9080,PLAINTEXT_DOCKER://kafka:9070
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LOG_DIRS=/kafka/kraft-combined-logs
    ports:
      - "9080:9080"
      - "9070:9070"
    volumes:
      - kafka_data:/kafka/kraft-combined-logs
    networks:
      - parsing-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: parsing-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9070
      - KAFKA_CLUSTERS_0_NAME=kraft
      - KAFKA_UI_AUTH_ENABLED=false
    networks:
      - parsing-net

  parsing-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parsing-service
    depends_on:
      - kafka
    environment:
      - configPath=/app/config.yaml
    ports:
      - "8070:8070"
    networks:
      - parsing-net

volumes:
  kafka_data:

networks:
  parsing-net:
    name: parsing-net
    driver: bridge
